version: '3'
services:
    nginx:
      restart: always
      container_name: nginx
      image: nginx
      ports:
      - 80:80
      - 443:443
      volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./nginx.conf/:/etc/nginx/nginx.conf 
      - /var/www/cert/:/var/www/cert/
      - ./logs/:/var/www/wwwlogs/